*see Discord for longer version*  - GameGUI.java UserPlayer object to "public static"  - SessionHandler.java temp declaration in save() method changed to 		"GameGUI.internalPlayer"  - due to the change in SessionHandler.java, the object is now picking 		up the current location
 ! still getting the error:
		java.io.NotSeralizableException: prototwopulled.UserPlayer
 ! either somewhere in UserPlayer.java and/or SessionHandler.java IMO